# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjy0kzD5EzGB7nZBc_GIMkxy2aRgCd2L
"""

import os
from os import listdir
import json
import torch
import scipy.misc
import numpy 
import glob

import torch.nn as nn
import torchvision.transforms as transforms

from torch.utils.data import Dataset
from PIL import Image

MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]

class DATA_TEST(Dataset):
    def __init__(self, args, mode ='train'):

        ''' set up basic parameters for dataset '''
        self.mode = mode
        self.data_dir = args.data_dir
        self.img_dir = os.path.join(self.data_dir)
        

        ''' read the data list '''
        list=[]

        for f in sorted(listdir(self.img_dir)):
            img_path = os.path.join(self.data_dir,f)
        
            list.append(img_path)

        array = numpy.array(list)
        self.data = array

    
        ''' set up image trainsform '''
        if self.mode == 'train':
            self.transform = transforms.Compose([
                              # transforms.RandomHorizontalFlip(0.5),
                               transforms.ToTensor(), # (H,W,C)->(C,H,W), [0,255]->[0, 1.0] RGB->RGB
                               transforms.Normalize(MEAN, STD)
                               ])

        elif self.mode == 'val' or self.mode == 'test':
            self.transform = transforms.Compose([
                               transforms.ToTensor(), # (H,W,C)->(C,H,W), [0,255]->[0, 1.0] RGB->RGB
                               transforms.Normalize(MEAN, STD)
                               ])


    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        ''' get data '''
        img_path = self.data[idx]
     
        ''' read image '''
        img = Image.open(img_path).convert('RGB')
     
       
        return self.transform(img)
